#!/usr/bin/env bash
#conda build hdf5
#conda build proj4
#conda build libnetcdf
#conda build lapack
#conda build clapack
conda build ossuuid
conda build libcf
#conda build esmf
#conda build jasper
#conda build g2clib
conda build yasm
conda build x264
conda build ffmpeg
conda build cmor
conda build vtk
#conda build libdrs_c
#conda build libcdms
conda build libdrs_f
conda build lats
conda build ezget
conda build cd77
