#!/usr/bin/env bash
conda build lapack
conda build clapack
conda build ossuuid
conda build libcf
conda build esmf
conda build jasper
conda build g2clib
conda build ossuuid
conda build libcf
conda build libcdms
conda build cdat_info
conda build distarray
conda build regrid2
conda build cdms2
conda build cdtime
conda build cdutil
conda build udunits2
conda build unidata
conda build genutil
conda build yasm
conda build x264
conda build ffmpeg
conda build vtk
conda build dv3d
conda build vcs
conda build vcsaddons
conda build thermo
conda build wk
conda build cmor
conda build pydebug
conda build uvcmetrics
conda build vistrails
conda build xmgrace
conda build esg
