#!/bin/sh -x

WORKDIR=$1
USER=cdat

#
# Arguments:
#    + WORKDIR - work directory where this script can write information to.
#
# Requirements:
#    + conda is installed, and added to PATH
#    + this script should be run on a repo top directory where 'recipe' directory resides
#    + this script assumes prep_for_build.py has been run on the repo directory and  
#      recipe/meta.yaml is generated.
#

source activate base
if [ `uname` == "Linux" ]; then
    OS=linux-64
else
    OS=osx-64
fi

if [ ! -d $WORKDIR ]; then
    mkdir $WORKDIR
fi

BASE_DIR=$(dirname "$0")
echo "BASE_DIR: $BASE_DIR"

prep_conda_env()
{
    conda clean --all
    conda install -n base conda-build anaconda conda-smithy
    conda update -y -q conda
    conda config --set anaconda_upload no
}

copy_repo_recipe()
{
    # copy project recipe to workdir
    cp -r $REPO_DIR/recipe $WORKDIR
}

get_conda_forge_configs() 
{
    # copy build configs from conda-forge to workdir

    # get conda_build_config.yaml -- which is the variant input file
    url="https://www.github.com/conda-forge/conda-forge-pinning-feedstock.git"
    git clone $url $WORKDIR/conda-forge-pinning-feedstock
    cp $WORKDIR/conda-forge-pinning-feedstock/recipe/conda_build_config.yaml $WORKDIR/recipe

    # get the migrations folder
    cp -r $WORKDIR/conda-forge-pinning-feedstock/recipe/migrations $WORKDIR/recipe
}

copy_build_yaml_to_repo()
{
    # copy yaml generated by rerender back to repo directory.
    cp -r $WORKDIR/.ci_support $REPO_DIR/
}

REPO_DIR=`pwd`

prep_conda_env

copy_repo_recipe

get_conda_forge_configs

conda smithy rerender

copy_build_yaml_to_repo

#
# here, if needed, we can specify --variants "{'python': ['2.7', '3.7']}"
#
cd $REPO_DIR
conda build recipe
